def execute_code(code: str, df):
    """
    Execute AI-generated Pandas code safely.

    Args:
        code (str): Python code generated by the LLM.
        df: Uploaded pandas DataFrame.

    Returns:
        tuple:
            (True, result) if execution succeeds.
            (False, error_message) if execution fails.
    """

    local_variables = {
        "df": df
    }

    try:
        result = eval(
            code,
            {},
            local_variables
        )

        return True, result

    except Exception as e:
        return False, str(e)